# Generated by Django 5.0.3 on 2024-06-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superf', models.IntegerField()),
                ('postvigi', models.IntegerField()),
                ('ptdeau', models.IntegerField()),
                ('trancherfeu', models.IntegerField()),
                ('typeEssence', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superf', models.IntegerField()),
                ('postvigi', models.IntegerField()),
                ('ptdeau', models.IntegerField()),
                ('trancherfeu', models.IntegerField()),
                ('typeEssence', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superf', models.IntegerField()),
                ('postvigi', models.IntegerField()),
                ('ptdeau', models.IntegerField()),
                ('trancherfeu', models.IntegerField()),
                ('typeEssence', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superf', models.IntegerField()),
                ('postvigi', models.IntegerField()),
                ('ptdeau', models.IntegerField()),
                ('trancherfeu', models.IntegerField()),
                ('typeEssence', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superf', models.IntegerField()),
                ('postvigi', models.IntegerField()),
                ('ptdeau', models.IntegerField()),
                ('trancherfeu', models.IntegerField()),
                ('typeEssence', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
