# Generated by Django 5.0.3 on 2024-06-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionincendie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a',
            name='postvigi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='b',
            name='postvigi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='c',
            name='postvigi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='d',
            name='postvigi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='e',
            name='postvigi',
            field=models.IntegerField(),
        ),
    ]
