# Generated by Django 5.0.3 on 2024-06-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionincendie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='Image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='b',
            name='Image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='c',
            name='Image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='d',
            name='Image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='e',
            name='Image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
