# Generated by Django 5.0.3 on 2024-06-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionincendie', '0002_alter_a_postvigi_alter_b_postvigi_alter_c_postvigi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a',
            name='image',
        ),
        migrations.RemoveField(
            model_name='b',
            name='image',
        ),
        migrations.RemoveField(
            model_name='c',
            name='image',
        ),
        migrations.RemoveField(
            model_name='d',
            name='image',
        ),
        migrations.RemoveField(
            model_name='e',
            name='image',
        ),
    ]
