# Generated by Django 5.0.3 on 2024-06-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionincendie', '0003_remove_a_image_remove_b_image_remove_c_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a',
            name='postvigi',
        ),
        migrations.RemoveField(
            model_name='a',
            name='ptdeau',
        ),
        migrations.RemoveField(
            model_name='a',
            name='trancherfeu',
        ),
        migrations.RemoveField(
            model_name='a',
            name='typeEssence',
        ),
        migrations.RemoveField(
            model_name='b',
            name='postvigi',
        ),
        migrations.RemoveField(
            model_name='b',
            name='ptdeau',
        ),
        migrations.RemoveField(
            model_name='b',
            name='trancherfeu',
        ),
        migrations.RemoveField(
            model_name='b',
            name='typeEssence',
        ),
        migrations.RemoveField(
            model_name='c',
            name='postvigi',
        ),
        migrations.RemoveField(
            model_name='c',
            name='ptdeau',
        ),
        migrations.RemoveField(
            model_name='c',
            name='trancherfeu',
        ),
        migrations.RemoveField(
            model_name='c',
            name='typeEssence',
        ),
        migrations.RemoveField(
            model_name='d',
            name='postvigi',
        ),
        migrations.RemoveField(
            model_name='d',
            name='ptdeau',
        ),
        migrations.RemoveField(
            model_name='d',
            name='trancherfeu',
        ),
        migrations.RemoveField(
            model_name='d',
            name='typeEssence',
        ),
        migrations.RemoveField(
            model_name='e',
            name='postvigi',
        ),
        migrations.RemoveField(
            model_name='e',
            name='ptdeau',
        ),
        migrations.RemoveField(
            model_name='e',
            name='trancherfeu',
        ),
        migrations.RemoveField(
            model_name='e',
            name='typeEssence',
        ),
    ]
