# Generated by Django 5.0.3 on 2024-06-12 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionincendie', '0004_remove_a_postvigi_remove_a_ptdeau_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='a',
            old_name='Superficie',
            new_name='superf',
        ),
        migrations.RenameField(
            model_name='b',
            old_name='Superficie',
            new_name='superf',
        ),
        migrations.RenameField(
            model_name='c',
            old_name='Superficie',
            new_name='superf',
        ),
        migrations.RenameField(
            model_name='d',
            old_name='Superficie',
            new_name='superf',
        ),
        migrations.RenameField(
            model_name='e',
            old_name='Superficie',
            new_name='superf',
        ),
    ]
